### ISSUE TITLE
MySQL and Docker - Error creating a database connection

### ISSUE THREAD

**Issue by CosmaTrix** [prisma/prisma2#1011]
Hi there,

I've set a tiny Docker environment with two services: Node.js (running express) and MySQL. Here's my `docker-compose.yml` file

```yml
version: "3.7"

services:
  app:
    image: node:12
    working_dir: /var/www
    ports:
      - "3010:3000"
    volumes:
      - ./app:/var/www
    command: sh -c 'yarn install && yarn dev'

  mysql:
    image: mysql:5.7
    ports:
      - "3310:3306"
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_USER: "prisma"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_PASSWORD: "secret"
      MYSQL_DATABASE: "prisma"

volumes:
  mysql: ~
```
I'm then being able to run `prisma2 init` from inside the container with the command `docker-compose exec app yarn prisma2 init`.
After following the wizard my `prisma.schema` file is outputted and the `datasource` field is
```
datasource db {
  provider = "mysql"
  url      = "mysql://prisma:secret@mysql:3306/prisma"
}
```
I can then run `docker-compose exec app yarn prisma2 lift save` and `docker-compose exec app yarn prisma2 lift up`. The migration runs smoothly and my database is updated. That means that the `app` container can communicate to the `mysql` one, doesn't it?

But, when I try to connect from the express app I get a connection error
```typescript
// server.ts
import express from "express";
import { Photon } from "@prisma/photon";

const app = express();
const photon = new Photon();

app.use("/", async (req, res) => {
  try {
    const users = await photon.users.findMany();
    return res.json(users);
  } catch (e) {
    return res.send(e.message);
  }
});

app.listen(3000, () => {
  console.log("Example app listening on port 3000!");
});
```
```typescript
// Invalid `photon.()` invocation in /var/www/src/index.ts:9:38
// Reason: Error in connector: Error creating a database connection.
```

Any idea of what's happening?

Thanks! 🙏
