### ISSUE TITLE
[Ubuntu 19.04] - Prisma2 Init hangs at "Preparing your database" when using MySQL database

### ISSUE THREAD

**Issue by izio38** [prisma/prisma2#522]
I just started by installing prisma2 globally, goes into `/stacks` and start with a boilerplate (GraphQL API (+Auth))

### Tree:
![image](https://user-images.githubusercontent.com/9900846/64485175-70cedb00-d21d-11e9-991c-22f5a6ae394a.png)

### Prisma2 version:
`prisma2@2.0.0-preview-10, binary version: 1b0c271f14ca00606f56c93717e228fe48c5603c`

### MySQL version:
`8.0.17` via docker hub (latest)

### Nodejs version:
`v10.15.2`

### Docker compose file:
```
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: ChangeMe
      MYSQL_DATABASE: izio
```

### Command I wrote:
`prisma2 init project`

### Database overview (via adminer):
![image](https://user-images.githubusercontent.com/9900846/64485221-0bc7b500-d21e-11e9-9e00-452e6f43774b.png)
![image](https://user-images.githubusercontent.com/9900846/64485224-171ae080-d21e-11e9-88b7-ea14890f1f10.png)

### Output:
![image](https://user-images.githubusercontent.com/9900846/64485212-e89d0580-d21d-11e9-95bf-2ff10d87a87c.png)

### After some tries:
It seems it worked with a PostgresQL server instance:
```
  kong-database:
    image: postgres
    restart: always
    container_name: kong-database
    environment:
      POSTGRES_DB: kong
      POSTGRES_USER: kong
      POSTGRES_PASSWORD: ChangeMe
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 3308:5432
    volumes:
      - kong-postgres-data:/var/lib/postgresql/data/pgdata
```
![image](https://user-images.githubusercontent.com/9900846/64485456-7e865f80-d221-11e9-885f-3baca09f9647.png)

If you need other informations, feel free to ask. However, I'm not an expert... :)
